---
title: Proker Tiap Bagian Panitia Ikhtibar Akbar 2 Dekade
description: idem
date: 10/20/2024
author: Team Ikhtibar Akbar 2 Dekade
categories: [ikhtibar, mdta]
draft: false
show: true
freeze: true
---

# Ketua (Sulthan A. Karimov)

# Sekretaris (M. Ilham Saputra)

## Proker

* Membuat Proposal Acara
* Membuat semua surat yang dibutuhkan dalam kepanitiaan:
  - Surat undangan Ikhtibar
  - Surat pemberitahuan Ikhtibar kepada Wali Santri
  - Surat permohonan untuk mengisi tausiah Ikhtibar

----------

# Bendahara

----------

# Lomba (Mbak Tista)

## Proker

* Menentukan jenis lomba untuk Ikhtibar
* Mengatur jalannya seluruh lomba Ikhtibar

## Surat yang dibutuhkan

* Membuat form penilaian lomba - bekerja sama dengan sekretaris

## Perlengkapan yang dibutuhkan

## Biaya yang dibutuhkan

----------

# Humas (Ahmad Nur Shodiq)

## Proker

* Distribusi surat-surat selama kepanitiaan
* Sosialisasi acara via poster - whatsapp - dll
* Mengurus Perijinan Acara

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

----------

# Dekorasi (Fajar Mahesa)

## Proker

* Membuat Konsep seluruh acara Ikhtibar

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Styrofoam
* Cat 
* Gliter 
* Lem 
* Cutting stiker 
* Triplek 
* Tenda 
* Banner 

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

* Ilham Setiawan 
* Rafa 
* Akbar 

----------

# Perlengkapan (Yoga Ananda)

## Proker

* Menyiapkan dan mengatur perlengkapan tiap bagian dalam kepanitiaan

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

----------

# Sound (Al-Falah Rizki)

## Proker

* Bertanggung jawab dalam menyiapkan sound untuk tiap acara Ikhtibar
* Mengecek sound sebelum hari-H 
* Memasang sound pada saat hari-H 

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Sound 
* Mixser 
* Mix werles
* Mix kabel 
* Stand mix 
* Stand sound 
* Baterai 
* Kabel parallel

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

----------

# Dokumentasi (Falka Derizqia)

## Proker

* Mendokumentasikan seluruh acara Ikhtibar
* Memilih dokumentasi acara terbaik untuk dicetak atau dipublikasikan
* Mempublikasikan dokumentasi acara
* Film Dokumenter Napak Tilas 20 Tahun MDTA Fisabilillah

## Surat yang dibutuhkan

* Surat untuk ketua MDTA
* Surat untuk alumni
* Surat untuk Pengurus MDTA
* Surat untuk 3 Santri yang masih aktif mengaji

## Perlengkapan yang dibutuhkan 

* Clapper Film (Handmade)
* Lighting (Handmade)
* Mic 
* Kamera (Jika memungkinkan 2 kamera)
* Kursi untuk Narasumber 
* Album Foto 
* Tripod Kamera 
* Stabilizer (Opsional)
* Memory Card
* Konsumsi untuk Narasumber dan Crew

## Biaya yang dibutuhkan 

* Clapper Film 
  * Kardus : Rp. 0 
  * Lem Tembak : Rp. 20.000 
  * Spidol : Rp. 0 
  * Gunting : Rp. 0 
* Lighting 
  * Lampu : Rp. 15.000
  * Kardus : Rp. 0 
  * Lem Tembak : Rp. 20.000 
  * Kabel : Rp. 15.000 
* Mic : Rp. 150.000 (Diusahakan untuk meminjam ke kantornya Falka)
* Kursi untuk Narasumber : Rp. 0 
* Album Foto : Rp. 0 
* Tripod Kamera : Rp. 0 
* Kamera : Rp. 0 
* Memory Card : Rp. 0 
* Konsumsi untuk Narasumber dan Crew : (Ditentukan Panitia)

## Personalia (anggota bagian)

* Director (Penanggung jawab keseluruhan) : Sulthan A. Karimov
* Sutradara (Falka Derizqia)
* Produser (Falka Derizqia)
* Penulis (Khaira Salistya Putri)
* Penata Kamera ( )
* Lighting ( )
* Perlengkapan Syuting (Yoga Ananda)
* Public Relation (Ahmad Nur Shodiq)
* Motion and Design Graphic (Falka Derizqia)

----------

# Konsumsi (Shofie)

## Proker

* Bertanggung jawab dalam menyiapkan konsumsi untuk tiap rentetan acara Ikhtibar

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Nampan 
* Piring 
* Keranjang buah 
* Kotak untuk tempat snack
* Plastik 1 kg 
* Teko 
* Gelas 

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

* Cania 
* Chika 
* Cinta 

----------

# Penerima Tamu (Riana Dian)

## Proker

* Bertanggung jawab dalam mengatur alur datang dan pulang Tamu
* Bertanggung jawab dalam mengatur posisi tamu yang hadir
* Menjaga meja penerimaan tamu di setiap acara Ikhtibar
* Bertanggung jawab dalam penyambutan tamu 

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Plastik sendal
* Meja penerima tamu
* Taplak meja
* Polybag

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

* Cania
* Chika 
* Anggun
* Alifya

----------

# Acara Puncak (Khaira Salistya Putri)

## Proker

* Membuat/memastikan konsep acara puncak
* Memastikan pengisi acara untuk acara puncak
* Mengatur urutan acara dari awal sampai akhir acara
* Menjadi time keeper pada hari H 
* Menentukan pelaksanaan gladi kotor dan gladi resik 
* Selalu berkoordinasi dengan seluruh pelatih pengisi acara  

## Surat yang dibutuhkan

* Surat undangan acara puncak untuk wali santri, RT setempat, RW, NU, MWC, Fatayat, IPPNU, IPNU, Ansor (sementara itu dulu)

## Perlengkapan yang dibutuhkan

* Nametag Panitia 
* Cue Card MC 
* Plastik Nametag Panitia 
  (sementara itu dulu)

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

* Alifya
* Aurel 
* Najwa

----------

# Festival 2 Dekade MDTA Fisabilillah (Anggi & Tiwi)

## Proker

* Mengumpulkan konsep seluruh acara pada Lomba Eksternal
* Mengatur urutan acara dari awal hingga akhir
* Mengatur jalannya acara pada hari H
* Menjadi time keeper pada hari H
* Bekerja sama dengan Humas dalam mengurus pendaftaran peserta acara

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

## Biaya yang dibutuhkan

# Lomba Hadroh (Anis Lusiani)

# Khitan (Pak Ubay)


