---
title: Proker Acara Puncak
description: idem
date: 10/20/2024
author: Team Ikhtibar Akbar 2 Dekade
categories: [ikhtibar, mdta]
draft: false
show: true
freeze: true
---

# Acara Puncak (Khaira Salistya Putri)

## Proker

* Membuat/memastikan konsep acara puncak
* Memastikan pengisi acara untuk acara puncak
* Mengatur urutan acara dari awal sampai akhir acara
* Menjadi time keeper pada hari H 
* Menentukan pelaksanaan gladi kotor dan gladi resik 
* Selalu berkoordinasi dengan seluruh pelatih pengisi acara  

## Surat yang dibutuhkan

* Surat undangan acara puncak untuk wali santri, RT setempat, RW, NU, MWC, Fatayat, IPPNU, IPNU, Ansor (sementara itu dulu)

## Perlengkapan yang dibutuhkan

* Nametag Panitia 
* Cue Card MC 
* Plastik Nametag Panitia 
  (sementara itu dulu)

## Biaya yang dibutuhkan

## Personalia (anggota bagian)

* Alifiya Zafira 
* Najwa Aulia Putri

## Konsep acara puncak

+-----------------------------+----------------------------------+
| MC Acara Puncak             | Alifya                           |
+=============================+==================================+
| MC Pembagian Hadroh         | Mas Ucup (on proses)             |
+-----------------------------+----------------------------------+
| Pelatih MC Acara Ikhtibar   | Mbak Nervi                       |
+-----------------------------+----------------------------------+
| Pelatih MC Pembagian Hadroh | (on proses)                      |
+-----------------------------+----------------------------------+
| Penampilan                  | 1. MDTA 1 (on proses)            |
|                             | 2. MDTA 2/3 (tari seribu tangan) |
+-----------------------------+----------------------------------+
| Pelatih Penampilan MDTA 1   | Mbak Nervi & Pengajar Sore       |
+-----------------------------+----------------------------------+
| Pelatih Penampilan MDTA 2/3 | (on proses)                      |
+-----------------------------+----------------------------------+
| Susuna Acara                | (on proses)                      |
+-----------------------------+----------------------------------+

Jumat, 14 Februari 2025

+-----+------------------+-----------------+----------+----------+-------------------+-------+
| No. | Acara            | Waktu           | Durasi   | Lighting | Perlengkapan      | Sound |
+=====+==================+=================+==========+==========+===================+=======+
| 1.  | Pembukaan        | 20.10 - 20.15   | 5 menit  |          | Selempang Khotmil |       |
+-----+------------------+-----------------+----------+----------+-------------------+-------+
| 2.  | Khataman         | 20.15 - 21.00   | 45 menit |          |                   |       |
+-----+------------------+-----------------+----------+----------+-------------------+-------+
| 3.  | Pembagian Hadiah | 21.00 - 22.00   | 60 menit |          |                   |       |
+-----+------------------+-----------------+----------+----------+-------------------+-------+
| 4.  | Doa Penutup      | 22.00 - 22.10   | 10 menit |          |                   |       |
+-----+------------------+-----------------+----------+----------+-------------------+-------+
| 5.  | Penutup          | 22.10 - selesai |          |          |                   |       |
+-----+------------------+-----------------+----------+----------+-------------------+-------+

Sabtu, 15 Februari 2025

+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| No. | Acara                 | Waktu           | Durasi   | Lighting | Perlengkapan | Sound |
+=====+=======================+=================+==========+==========+==============+=======+
| 1.  | Pembukaan             | 20.10 - 20.15   | 5 menit  |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 2.  | Pembagian Hadiah      | 20.15 - 20.45   | 30 menit |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 3.  | Break                 | 20.45 - 20.50   | 5 menit  |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 4.  | Sambutan :            |                 |          |          |              |       |
|     | - Ketua Panitia       | 20.50 - 20.57   | 7 menit  |          |              |       |
|     | - Wali Santri         | 20.57 - 21.04   | 7 menit  |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 5.  | Khataman              | 21.04 - 21.49   | 45 menit |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 6.  | Sambutan :            |                 |          |          |              |       |
|     | - Ketua MDTA          | 21.49 - 21.19   | 30 menit |          |              |       |
|     | - Aparatur Lingkungan | 21.19 - 21.26   | 7 menit  |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 7.  | Ceramah               | 21.26 - 21.56   | 30 menit |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 8.  | Doa Penutup           | 21.56 - 22.06   | 10 menit |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 9.  | Penutup               | 22.06 - 22.11   | 5 menit  |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+
| 10. | Sungkeman             | 22.11 - selesai |          |          |              |       |
+-----+-----------------------+-----------------+----------+----------+--------------+-------+

----------
