---
title: Proker Film Napak Tilas MDTA
description: idem
date: 10/20/2024
author: Team Ikhtibar Akbar 2 Dekade
categories: [ikhtibar, mdta]
draft: false
show: true
freeze: true
---

# Dokumentasi (Falka Derizqia)

## Proker

* Mendokumentasikan seluruh acara Ikhtibar
* Memilih dokumentasi acara terbaik untuk dicetak atau dipublikasikan
* Mempublikasikan dokumentasi acara
* Film Dokumenter Napak Tilas 20 Tahun MDTA Fisabilillah

## Surat yang dibutuhkan

* Surat untuk ketua MDTA
* Surat untuk alumni
* Surat untuk Pengurus MDTA
* Surat untuk 3 Santri yang masih aktif mengaji

## Perlengkapan yang dibutuhkan 

* Clapper Film (Handmade)
* Lighting (Handmade)
* Mic 
* Kamera (Jika memungkinkan 2 kamera)
* Kursi untuk Narasumber 
* Album Foto 
* Tripod Kamera 
* Stabilizer (Opsional)
* Memory Card
* Konsumsi untuk Narasumber dan Crew

## Biaya yang dibutuhkan 

+------------------------------------------------------+----------------------+
| keterangan                                           | jumlah               |
+======================================================+======================+
| ### Clapper Film:                                                           |
+------------------------------------------------------+----------------------+
| * Kardus                                             | * Rp. 0              |
| * Lem Tembak                                         | * Rp. 20.000         |
| * Spidol                                             | * Rp. 0              |
| * Gunting                                            | * Rp. 0              |
+------------------------------------------------------+----------------------+
| ### Lighting:                                                               |
+------------------------------------------------------+----------------------+
| * Lampu                                              | * Rp. 15.000         |
| * Kardus                                             | * Rp. 0              |
| * Lem Tembak                                         | * Rp. 20.000         |
| * Kabel                                              | * Rp. 15.000         |
+------------------------------------------------------+----------------------+
| * Mic (Diusahakan untuk meminjam ke kantornya Falka) | Rp. 150.000          |
+------------------------------------------------------+----------------------+
| * Kursi untuk Narasumber                             | Rp. 0                |
+------------------------------------------------------+----------------------+
| * Album Foto                                         | Rp. 0                |
+------------------------------------------------------+----------------------+
| * Tripod Kamera                                      | Rp. 0                |
+------------------------------------------------------+----------------------+
| * Kamera                                             | Rp. 0                |
+------------------------------------------------------+----------------------+
| * Memory Card                                        | Rp. 0                |
+------------------------------------------------------+----------------------+
| * Konsumsi untuk Narasumber dan Crew                 | (Ditentukan Panitia) |
+------------------------------------------------------+----------------------+

## Personalia (anggota bagian)

* Director (Penanggung jawab keseluruhan) : Sulthan A. Karimov
* Sutradara (Falka Derizqia)
* Produser (Falka Derizqia)
* Penulis (Khaira Salistya Putri)
* Penata Kamera ( )
* Lighting ( )
* Perlengkapan Syuting (Yoga Ananda)
* Public Relation (Ahmad Nur Shodiq)
* Motion and Design Graphic (Falka Derizqia)

----------
