---
title: Proker Tiap Bagian Panitia Ikhtibar Akbar 2 Dekade
description: idem
date: 10/20/2024
author: Team Ikhtibar Akbar 2 Dekade
categories: [ikhtibar, mdta]
draft: false
show: true
freeze: true
---

# Ketua (Sulthan A. Karimov)

# Sekretaris (M. Ilham Saputra)

## Proker

* Membuat Proposal Acara
* Membuat semua surat yang dibutuhkan dalam kepanitiaan:
  - Surat undangan Ikhtibar
  - Surat pemberitahuan Ikhtibar kepada Wali Santri
  - Surat permohonan untuk mengisi tausiah Ikhtibar

----------

# Bendahara

----------

# Humas (Ahmad Nur Shodiq)

## Proker

* Distribusi surat-surat selama kepanitiaan
* Sosialisasi acara via poster - whatsapp - dll
* Mengurus Perijinan Acara

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

----------

# Dekorasi (Fajar Mahesa)

## Proker

* Membuat Konsep seluruh acara Ikhtibar

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Styrofoam
* Cat 
* Gliter 
* Lem 
* Cutting stiker 
* Triplek 
* Tenda 
* Banner 

----------

# Perlengkapan (Yoga Ananda)

## Proker

* Menyiapkan dan mengatur perlengkapan tiap bagian dalam kepanitiaan

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

----------

# Sound (Al-Falah Rizki)

## Proker

* Bertanggung jawab dalam menyiapkan sound untuk tiap acara Ikhtibar
* Mengecek sound sebelum hari-H 
* Memasang sound pada saat hari-H 

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Sound 
* Mixser 
* Mix werles
* Mix kabel 
* Stand mix 
* Stand sound 
* Baterai 
* Kabel parallel

----------

# Dokumentasi (Falka Derizqia)

## Proker

* Mendokumentasikan seluruh acara Ikhtibar
* Memilih dokumentasi acara terbaik untuk dicetak atau dipublikasikan
* Mempublikasikan dokumentasi acara
* Film Dokumenter Napak Tilas 20 Tahun MDTA Fisabilillah

## Surat yang dibutuhkan

* Surat untuk ketua MDTA
* Surat untuk alumni
* Surat untuk Pengurus MDTA
* Surat untuk 3 Santri yang masih aktif mengaji

## Perlengkapan yang dibutuhkan 

* Clapper Film (Handmade)
* Lighting (Handmade)
* Mic 
* Kamera (Jika memungkinkan 2 kamera)
* Kursi untuk Narasumber 
* Album Foto 
* Tripod Kamera 
* Stabilizer (Opsional)
* Memory Card
* Konsumsi untuk Narasumber dan Crew

----------

# Konsumsi (Shofie)

## Proker

* Bertanggung jawab dalam menyiapkan konsumsi untuk tiap rentetan acara Ikhtibar

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Nampan 
* Piring 
* Keranjang buah 
* Kotak untuk tempat snack
* Plastik 1 kg 
* Teko 
* Gelas 

----------

# Penerima Tamu (Riana Dian)

## Proker

* Bertanggung jawab dalam mengatur alur datang dan pulang Tamu
* Bertanggung jawab dalam mengatur posisi tamu yang hadir
* Menjaga meja penerimaan tamu di setiap acara Ikhtibar
* Bertanggung jawab dalam penyambutan tamu 

## Surat yang dibutuhkan

## Perlengkapan yang dibutuhkan

* Plastik sendal
* Meja penerima tamu
* Taplak meja
* Polybag

----------
